In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
insurance = pd.read_csv("insurance.csv")
insurance

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
insurance_one = pd.get_dummies(insurance)
insurance_one

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,True,False,False,True,False,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False,False,False,True,False
2,28,33.000,3,4449.46200,False,True,True,False,False,False,True,False
3,33,22.705,0,21984.47061,False,True,True,False,False,True,False,False
4,32,28.880,0,3866.85520,False,True,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False,False,True,False,False
1334,18,31.920,0,2205.98080,True,False,True,False,True,False,False,False
1335,18,36.850,0,1629.83350,True,False,True,False,False,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False,False,False,False,True
1337,61,29.070,0,29141.36030,True,False,False,True,False,True,False,False

In [4]:
X = insurance_one.drop('charges', axis=1)
y = insurance_one['charges']

In [5]:
X.head()

,age,bmi,children,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,True,False,False,True,False,False,False,True
1,18,33.770,1,False,True,True,False,False,False,True,False
2,28,33.000,3,False,True,True,False,False,False,True,False
3,33,22.705,0,False,True,True,False,False,True,False,False
4,32,28.880,0,False,True,True,False,False,True,False,False

In [6]:
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

# Create the training and testing datasets

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [8]:
len(X), len(X_train), len(X_test)

(1338, 1070, 268)

In [9]:
len(y), len(y_train), len(y_test)

(1338, 1070, 268)

In [22]:
tf.random.set_seed(42)
insurance_model = tf.keras.Sequential([
    tf.keras.layers.Dense(12),
    tf.keras.layers.Dense(9),
    tf.keras.layers.Dense(8),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])
insurance_model.compile(loss=tf.keras.losses.mae,
                        optimizer=tf.keras.optimizers.Adam(),
                        metrics=["mae"])
insurance_model.fit(X_train, y_train, epochs=100)

Epoch 1/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 356us/step - loss: 13218.2568 - mae: 13218.2568
Epoch 2/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - loss: 13085.5254 - mae: 13085.5254
Epoch 3/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 318us/step - loss: 12756.2031 - mae: 12756.2031
Epoch 4/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 315us/step - loss: 11844.8535 - mae: 11844.8535
Epoch 5/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - loss: 9730.6777 - mae: 9730.6777
Epoch 6/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 288us/step - loss: 7481.1528 - mae: 7481.1528
Epoch 7/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 288us/step - loss: 7303.4248 - mae: 7303.4248
Epoch 8/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 279us/step - loss: 7279.1260 - mae: 7279.1260
Epoch 9/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 292us/step - loss: 7250.8906 - mae: 7250.8906
Epoch 10/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 272us/step - loss: 7224.5156 - mae: 7224.5156
Epoch 11/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 278us/step - loss: 7197.0303 - mae: 7197.0303
Epoch 12/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 306us/step - loss: 7169.4639 - mae: 7169.4639
Epoch 13/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 292us/step - loss: 7140.0776 - mae: 7140.0776
Epoch 14/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - loss: 7110.5903 - mae: 7110.5903
Epoch 15/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - loss: 7080.7471 - mae: 7080.7471
Epoch 16/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 272us/step - loss: 7049.6025 - mae: 7049.6025
Epoch 17/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 270us/step - loss: 7018.1133 - mae: 7018.1133
Epoch 18/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - loss: 6986.2803 - mae: 6986.2803
Epoch 19/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 277us/step - loss: 6952.0005 - mae: 6952.0005
Epoch 20/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - loss: 6916.1523 - mae: 6916.1523
Epoch 21/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 280us/step - loss: 6879.0229 - mae: 6879.0229
Epoch 22/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 271us/step - loss: 6842.4175 - mae: 6842.4175
Epoch 23/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 285us/step - loss: 6804.2070 - mae: 6804.2070
Epoch 24/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - loss: 6763.9243 - mae: 6763.9243
Epoch 25/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 272us/step - loss: 6720.7710 - mae: 6720.7710
Epoch 26/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - loss: 6674.9565 - mae: 6674.9565
Epoch 27/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 279us/step - loss: 6628.8584 - mae: 6628.8584
Epoch 28/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 280us/step - loss: 6582.9995 - mae: 6582.9995
Epoch 29/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 274us/step - loss: 6537.5972 - mae: 6537.5972
Epoch 30/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - loss: 6496.2109 - mae: 6496.2109
Epoch 31/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - loss: 6462.6401 - mae: 6462.6401
Epoch 32/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 286us/step - loss: 6439.8496 - mae: 6439.8496
Epoch 33/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 290us/step - loss: 6422.1592 - mae: 6422.1592
Epoch 34/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 280us/step - loss: 6405.5850 - mae: 6405.5850
Epoch 35/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 268us/step - loss: 6390.1323 - mae: 6390.1323
Epoch 36/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 269us/step - loss: 6375.4863 - mae: 6375.4863
Epoch 37/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 270us/step - loss: 6361.0767 - mae: 6361.0767
Epoch 38/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 272us/step - loss: 6346.5732 - mae: 6346.5732
Epoch 39/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 279us/step - loss: 6332.0127 - mae: 6332.0127
Epoch 40/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - loss: 6316.9575 - mae: 6316.9575
Epoch 41/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - loss: 6301.5127 - mae: 6301.5127
Epoch 42/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 278us/step - loss: 6286.2993 - mae: 6286.2993
Epoch 43/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 270us/step - loss: 6270.2607 - mae: 6270.2607
Epoch 44/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - loss: 6253.8994 - mae: 6253.8994
Epoch 45/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 290us/step - loss: 6237.2461 - mae: 6237.2461
Epoch 46/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 273us/step - loss: 6219.5747 - mae: 6219.5747
Epoch 47/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 290us/step - loss: 6201.4009 - mae: 6201.4009
Epoch 48/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 278us/step - loss: 6182.5083 - mae: 6182.5083
Epoch 49/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - loss: 6162.7920 - mae: 6162.7920
Epoch 50/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - loss: 6142.0415 - mae: 6142.0415
Epoch 51/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - loss: 6120.4180 - mae: 6120.4180
Epoch 52/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 273us/step - loss: 6097.3447 - mae: 6097.3447
Epoch 53/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 308us/step - loss: 6072.6104 - mae: 6072.6104
Epoch 54/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 285us/step - loss: 6047.2373 - mae: 6047.2373
Epoch 55/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - loss: 6020.3940 - mae: 6020.3940
Epoch 56/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 276us/step - loss: 5992.0200 - mae: 5992.0200
Epoch 57/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 278us/step - loss: 5961.8965 - mae: 5961.8965
Epoch 58/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 272us/step - loss: 5928.5474 - mae: 5928.5474
Epoch 59/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 265us/step - loss: 5893.2515 - mae: 5893.2515
Epoch 60/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - loss: 5855.5483 - mae: 5855.5483
Epoch 61/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 275us/step - loss: 5813.0483 - mae: 5813.0483
Epoch 62/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 288us/step - loss: 5766.9663 - mae: 5766.9663
Epoch 63/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 270us/step - loss: 5716.4082 - mae: 5716.4082
Epoch 64/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 277us/step - loss: 5659.2119 - mae: 5659.2119
Epoch 65/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 280us/step - loss: 5594.6997 - mae: 5594.6997
Epoch 66/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 273us/step - loss: 5523.9658 - mae: 5523.9658
Epoch 67/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 298us/step - loss: 5440.8633 - mae: 5440.8633
Epoch 68/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 275us/step - loss: 5351.3618 - mae: 5351.3618
Epoch 69/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 274us/step - loss: 5240.7231 - mae: 5240.7231
Epoch 70/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 287us/step - loss: 5109.3516 - mae: 5109.3516
Epoch 71/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 271us/step - loss: 4961.8364 - mae: 4961.8364
Epoch 72/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 277us/step - loss: 4780.4604 - mae: 4780.4604
Epoch 73/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 276us/step - loss: 4567.3135 - mae: 4567.3135
Epoch 74/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - loss: 4320.1655 - mae: 4320.1655
Epoch 75/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 279us/step - loss: 4071.4426 - mae: 4071.4426
Epoch 76/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 267us/step - loss: 3907.4121 - mae: 3907.4121
Epoch 77/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 266us/step - loss: 3844.1257 - mae: 3844.1257
Epoch 78/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 267us/step - loss: 3813.0825 - mae: 3813.0825
Epoch 79/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - loss: 3809.3542 - mae: 3809.3542
Epoch 80/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 275us/step - loss: 3791.2844 - mae: 3791.2844
Epoch 81/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 280us/step - loss: 3779.0129 - mae: 3779.0129
Epoch 82/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 273us/step - loss: 3777.6777 - mae: 3777.6777
Epoch 83/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - loss: 3757.8711 - mae: 3757.8711
Epoch 84/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 269us/step - loss: 3750.1462 - mae: 3750.1462
Epoch 85/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 291us/step - loss: 3744.9651 - mae: 3744.9651
Epoch 86/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 281us/step - loss: 3741.1741 - mae: 3741.1741
Epoch 87/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 280us/step - loss: 3737.2666 - mae: 3737.2666
Epoch 88/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 500us/step - loss: 3735.9192 - mae: 3735.9192
Epoch 89/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - loss: 3727.0457 - mae: 3727.0457
Epoch 90/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 290us/step - loss: 3719.0420 - mae: 3719.0420
Epoch 91/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - loss: 3715.7051 - mae: 3715.7051
Epoch 92/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 273us/step - loss: 3710.0022 - mae: 3710.0022
Epoch 93/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 289us/step - loss: 3707.5811 - mae: 3707.5811
Epoch 94/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 276us/step - loss: 3703.8433 - mae: 3703.8433
Epoch 95/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 301us/step - loss: 3701.9568 - mae: 3701.9568
Epoch 96/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - loss: 3699.0667 - mae: 3699.0667
Epoch 97/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 288us/step - loss: 3695.1006 - mae: 3695.1006
Epoch 98/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - loss: 3696.9316 - mae: 3696.9316
Epoch 99/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 283us/step - loss: 3693.8191 - mae: 3693.8191
Epoch 100/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 359us/step - loss: 3688.5457 - mae: 3688.5457

In [25]:
insurance_model.evaluate(X_test, y_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - loss: 3653.6436 - mae: 3653.6436

[3586.4072265625, 3586.4072265625]